apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w4i2r57u9-nodejs
  janus-idp.io/tekton: w4i2r57u9-nodejs
  backstage.io/kubernetes-id: w4i2r57u9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w4i2r57u9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
